apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecg-classifier-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecg-classifier
  template:
    metadata:
      labels:
        app: ecg-classifier
    spec:
      containers:
      - name: ecg-api
        image: <YOUR_ACR_NAME>.azurecr.io/ecg-api:v1
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: ecg-classifier-service
spec:
  type: LoadBalancer
  selector:
    app: ecg-classifier
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000